name: 'Send Request'

description: 'Send request to lohas server'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  artifact-id:
    description: 'Id of artifact'
    required: true
  jwt-secret:
    description: 'jwt secret key'
    required: true
  issue-number:
    description: 'main issue number'
    required: true
  api-url:
    description: 'Webhook API endpoint url'
    required: true

outputs:
  success:
    description: 'boolean string of add comment ("true"/"false")'

runs:
  using: 'node16'
  main: 'dist/index.js'
